[package]
name = "mc-util-repr-bytes"
version = "0.1.0"
authors = ["MobileCoin"]
edition = "2018"
readme = "README.md"

[dependencies]
generic-array = "0.13"

[dev-dependencies]
prost = { version = "0.6.1", default-features = false, features = ["prost-derive"] }
serde = { version = "1.0", default-features = false, features = ["alloc"] }
serde_cbor = { version = "0.11.1", default-features = false, features = ["alloc"] }
